[package]
name = "frontend"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
zoon.workspace = true
uuid = { version = "1.10.0", default-features = false, features = ["js", "v4", "serde"]}
